Test8
RokuMikami/QAI_onboarding_TypeScript pull request #7
Opened 2024-04-09 12:01 UTC by RokuMikami

fizzBuzzの実装およびfizzBuzzをテストするコードを実装しましたのでレビューをお願いします！

---
### ◾️レビューして欲しい箇所
fizzBuzz関数の実装とfizzBuzz関数をテストするコードの実装に問題がないか

- [ ] fizzBuzz.ts/js
- [ ] fizzBuzz.test.ts/js
- [ ] 現在のファイル構成でnpm run testできるかどうか

---
### ◾️変更点
- [ ] fizzBuzz関数を実装
- [ ] fizzBuzz関数をテストするコードを実装

---
### ◾️期待される結果
- [ ] 3の倍数を渡したらFizzを返すこと
- [ ] 5の倍数を渡したらBuzzを返すこと
- [ ] 3と5の倍数を渡したらFizzBuzzを返すこと
- [ ] 3の倍数でも5の倍数でもなかったら渡した値そのままで返すこと
- [ ] 1未満の数字を渡した場合、エラーを返すこと
- [ ] 30より大きい数字を渡した場合、エラーを返すこと
- [ ] 上記内容をテストできていること

---
### ◾️実装に関しての備考
・input全てに対して網羅的にテストはしていません
・各同値クラスから3つの代表値を選出してテストしています
・number型以外の引数を受け取ることは想定していません

2024-04-09 12:02 UTC, RokuMikami commented
node_moduleをブランチから削除しました！

2024-04-10 00:12 UTC, undesicimo commented
> node_moduleをブランチから削除しました！

削除した場合、手元で動かなくなるかつ、プルした側から同じく大量の差分が出るので
gitignore見ていただければと思います

https://qiita.com/anqooqie/items/110957797b3d5280c44f

2024-04-10 03:41 UTC, kazukisato-b commented on typescript_Assignment_2/fizzBuzz.test.ts
> +test.each([
下記のような感じでdescribeで正常系と異常系をグループ化してあげると、より分かりやすいと思いました。
https://jestjs.io/ja/docs/api#describename-fn
```
describe("正常系", () => {
  test("テスト名1", () => {
    /* テスト内容 */
  });
  test("テスト名2", () => {
    /* テスト内容 */
  });
});
describe("異常系", () => {
  test("テスト名1", () => {
    /* テスト内容 */
  });
  test("テスト名2", () => {
    /* テスト内容 */
  });
});
```

2024-04-10 03:41 UTC, kazukisato-b commented on typescript_Assignment_2/fizzBuzz.test.ts
> +  [3, msg1],
毎回msg1を渡す必要はありますか？
全て結果は同じ"Fizz"になると思うので毎回渡さなくても良いと思いました！

2024-04-10 03:41 UTC, kazukisato-b commented on typescript_Assignment_2/fizzBuzz.js
今回の課題においてはtsファイルだけで確認できるのでjsファイルは不要です。
Node.js / TypeScript課題の際はtsからjsへの変換の流れを把握していただくために、jsファイルもプッシュしていただきました！

2024-04-10 03:41 UTC, kazukisato-b commented on typescript_Assignment_2/fizzBuzz.test.js
https://github.com/RokuMikami/QAI_onboarding_TypeScript/pull/7#discussion_r1558795051

2024-04-10 08:22 UTC, undesicimo requested changes

2024-04-10 08:22 UTC, undesicimo commented on typescript_Assignment_2/.DS_Store
こちらもgitignoreして頂ければと思います！
https://zenn.dev/rabee/articles/gitignore-global-ds-store

2024-04-10 08:22 UTC, undesicimo commented on typescript_Assignment_2/fizzBuzz.js
Must: トランスパイルされたファイルも基本不要です！

2024-04-10 09:20 UTC, RokuMikami commented
> > node_moduleをブランチから削除しました！
> 
> 削除した場合、手元で動かなくなるかつ、プルした側から同じく大量の差分が出るので gitignore見ていただければと思います
> 
> https://qiita.com/anqooqie/items/110957797b3d5280c44f

.gitignoreを作成しました！

2024-04-10 09:21 UTC, RokuMikami commented on typescript_Assignment_2/fizzBuzz.test.ts
> +test.each([
describeしました！（describe.eachも使ってみました！）

2024-04-10 09:21 UTC, RokuMikami commented on typescript_Assignment_2/fizzBuzz.test.ts
> +  [3, msg1],
一回で渡せば済むように調整しました！

2024-04-10 09:22 UTC, RokuMikami commented on typescript_Assignment_2/fizzBuzz.js
jsファイルを削除しました！
加えてローカルリポジトリで動かした際にはjsファイルはできてしまうものだと思うので、gitignoreで無視するようにしました！

2024-04-10 09:23 UTC, RokuMikami commented on typescript_Assignment_2/fizzBuzz.test.js
対応しました！

2024-04-10 23:31 UTC, undesicimo commented on typescript_Assignment_2/.gitignore
> +fizzBuzz.js
Must: 出力をディレクトリにまとめて、そのディレクトリを除外しましょう！
仮にプロフェクトが大きくなりトランスパイル出力が増えると、一つ一つ定義する必要あります。

https://qiita.com/RyosukeSomeya/items/3ef53eb42b890f419472

2024-04-11 01:03 UTC, kazukisato-b commented on typescript_Assignment_2/fizzBuzz.test.ts
> +    [1, "1"],
消し忘れだと思いますが、"1"のほうは不要だと思います。

2024-04-11 01:12 UTC, kazukisato-b commented on typescript_Assignment_2/fizzBuzz.test.ts
> +    "30より大きい数字を渡した場合、エラーを返すこと",
1未満のテストになってしまっているので、正しい数値に修正お願いいたします。

2024-04-11 03:41 UTC, RokuMikami commented on typescript_Assignment_2/.gitignore
> +fizzBuzz.js
対応しました！

2024-04-11 03:41 UTC, RokuMikami commented on typescript_Assignment_2/fizzBuzz.test.ts
> +    [1, "1"],
たしかに・・・消します！

2024-04-11 03:42 UTC, RokuMikami commented on typescript_Assignment_2/fizzBuzz.test.ts
> +    "30より大きい数字を渡した場合、エラーを返すこと",
ケアレスミスですみません・・・

2024-04-11 04:28 UTC, RokuMikami commented
各種修正完了しました！
（srcフォルダとtestsフォルダも作ってみました）

2024-04-11 04:53 UTC, kazukisato-b approved these changes
👍

2024-04-11 04:57 UTC, undesicimo approved these changes
![image](https://github.com/RokuMikami/QAI_onboarding_TypeScript/assets/105863111/85a25494-4884-497e-abed-edad91d3bbed)

2024-04-11 13:13 UTC, merged

2024-04-11 13:13 UTC, RokuMikami commented
レビューありがとうございました！マージしてブランチ消します！